<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quests [
        <!ELEMENT quests    (quest+)>
        <!ELEMENT quest     (title, step+)>
        <!ELEMENT title     (#PCDATA)>
        <!ELEMENT quests    xmlns        CDATA  #IMPLIED>
        <!ELEMENT quests    xmlns:xhtml  CDATA  #IMPLIED>
        <!ELEMENT quest     id           ID     #IMPLIED>
        <!ELEMENT step      id           ID     #IMPLIED>
]>

<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<quests xmlns="quests.php/" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <quest id="1">
 
        <title>Quest Title 1</title>
        
        <!-- quest steps dialog -->
        <step id="1">This is step 1 of the quest</step>
        <step id="2">This is step 2 of the quest</step>
        <step id="3">This is step 3 of the quest</step>
        <step id="4">This is step 4 of the quest</step>
        <step id="5">This is the completed step of the quest</step>

    </quest>
</quests>
